### ISSUE TITLE
Changes in "Zákon č. 326/1999 Sb."

### ISSUE THREAD

**Issue by detochenko** [fernflower/ciziproblem#37]
Dear Inessa,

Now, according to 66th version of act # 326/1999, a deadline for approval of application to permanent residence is set not "§ 169t odst. 6 písm. g) bod 1., 2., 3. ZPC" , but "§ 169t odst. 6 písm. **h)** bod 1., 2., 3. ZPC". Information on [https://www.mvcr.cz/clanek/lhuty-a-pocitani-casu.aspx](url) right now is old and incorrect. For assure visit: [https://www.zakonyprolidi.cz/cs/1999-326/zneni-20230920#f6092331](url)

Thank you very much for your work(!) and best regards,
Detochenko Nikita

**Comment by fernflower** [comment]
Thanks a lot! Will fix tonight :)

**Comment by fernflower** [comment]
Should be fine now. I will leave the pr open for some time in case some more issues emerge.
I'll also probably report the issue to the Minvnitra as having such critical information wrong on the official website sucks big time. 
Thank again for the report!
